services:
  - type: web
    name: gold-prices-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
